version: '3.1'

services:

  topic_modelling_service:
    image: python:3.11
    working_dir: /app
    volumes:
      - ./topic_modelling_service/:/app/
    command:
      bash -c "pip install poetry uvicorn && ls &&
      poetry export -f requirements.txt > requirements.txt &&
      pip install -r requirements.txt &&
      cd src &&
      uvicorn main:app --host 0.0.0.0 --port 8052"
    ports:
      - 9051:8052


  presentation_generator_service:
    image: python:3.11
    working_dir: /app
    volumes:
      - ./presentation_generator_service/:/app/
    command:
      bash -c "pip install poetry &&
      poetry export -f requirements.txt > requirements.txt &&
      pip install -r requirements.txt &&
      cd src &&
      uvicorn main:app --host 0.0.0.0 --port 8052"
    links:
     - topic_modelling_service
    networks:
      - topic_modelling
    ports:
      - 10051:8052
  

networks:
  topic_modelling:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
